### ISSUE TITLE
remove stale branches

### ISSUE THREAD

**Issue by josephmasson26** [josephmasson26/DiagnoseMe#89]
do it. 

also i cant make labels can you make us a maintenance one for this issue

**Comment by NamkhangNLe** [comment]
> do it.
> 
> also i cant make labels can you make us a maintenance one for this issue

Created, but what do you want the description to be? As in what is its intended purpose? I don't mind making them but it doesn't let you?

**Comment by josephmasson26** [comment]
i'm just on mobile rn

**Comment by NamkhangNLe** [comment]
> i'm just on mobile rn
not a problem, just wanted to make sure it wasn't a permissions issue or something.
